# Generated by Django 5.0.13 on 2025-05-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='taiKhoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenTaiKhoan', models.CharField(max_length=50)),
                ('matKhau', models.CharField(max_length=50)),
                ('hoTen', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('soDienThoai', models.CharField(max_length=15)),
                ('diaChi', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
