# Generated by Django 5.0.13 on 2025-06-05 13:17

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Danhmuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100, unique=True)),
                ('ordering', models.IntegerField(default=0)),
                ('loai', models.CharField(choices=[('tintuc', 'Tin tức'), ('cuocthi', 'Cuộc thi')], default='tintuc', max_length=20)),
                ('layout', models.CharField(choices=[('list', 'List'), ('grid', 'Grid')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('ordering', models.IntegerField(default=0)),
                ('content', ckeditor.fields.RichTextField(default='Nội dung đang cập nhật')),
                ('publish_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('danhmuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fintech.danhmuc')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='fintech.post')),
            ],
        ),
    ]
