# Generated by Django 4.1.7 on 2025-06-07 13:18

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fintech', '0002_danhmuc_post_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='taiKhoan',
        ),
        migrations.AlterField(
            model_name='danhmuc',
            name='loai',
            field=models.CharField(choices=[('noibo', 'Tin tức nội bộ'), ('quocte', 'Tin tức quốc tế')], default='noibo', max_length=20),
        ),
        migrations.CreateModel(
            name='taiKhoan',
            fields=[
            ],
            options={
                'verbose_name': 'Tài khoản người dùng',
                'verbose_name_plural': 'Tài khoản người dùng',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
