# Generated by Django 4.1.7 on 2025-06-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0003_delete_taikhoan_alter_danhmuc_loai_taikhoan'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
