# Generated by Django 4.1.7 on 2025-06-09 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0007_dangkytuyensinh'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DangKyTuyenSinh',
        ),
    ]
